FROM --platform=linux/arm64 registry.fedoraproject.org/fedora:42 AS target-sysroot

RUN dnf --assumeyes install \
        bluez-libs-devel \
        dbus-devel \
        glibc-devel \
        libstdc++-devel \
    && dnf clean all

FROM --platform=linux/amd64 registry.fedoraproject.org/fedora:42

RUN dnf --assumeyes install \
        ca-certificates \
        clang-devel \
        gcc \
        gcc-aarch64-linux-gnu \
        gcc-c++ \
        gcc-c++-aarch64-linux-gnu \
        make \
        pkg-config \
    && dnf clean all

COPY --from=target-sysroot /usr/include/ /usr/aarch64-linux-gnu/sys-root/usr/include/
COPY --from=target-sysroot /usr/lib/ /usr/aarch64-linux-gnu/sys-root/usr/lib/
COPY --from=target-sysroot /usr/lib64/ /usr/aarch64-linux-gnu/sys-root/usr/lib64/
COPY --from=target-sysroot /lib64/ /usr/aarch64-linux-gnu/sys-root/lib64/

RUN mkdir -p /usr/aarch64-linux-gnu/sys-root/lib \
    && ln -sf ../usr/lib/ld-linux-aarch64.so.1 /usr/aarch64-linux-gnu/sys-root/lib/ld-linux-aarch64.so.1 \
    && ln -sf /usr/aarch64-linux-gnu/sys-root/lib64/libstdc++.so.6 /usr/lib/gcc/aarch64-linux-gnu/15/libstdc++.so \
    && ln -sf /usr/aarch64-linux-gnu/sys-root/lib64/libgcc_s.so.1 /usr/lib/gcc/aarch64-linux-gnu/15/libgcc_s.so

ENV CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc
ENV CC_aarch64_unknown_linux_gnu=aarch64-linux-gnu-gcc
ENV CXX_aarch64_unknown_linux_gnu=aarch64-linux-gnu-g++
ENV AR_aarch64_unknown_linux_gnu=aarch64-linux-gnu-ar
ENV CXXFLAGS_aarch64_unknown_linux_gnu="-isystem /usr/aarch64-linux-gnu/sys-root/usr/include/c++/15 -isystem /usr/aarch64-linux-gnu/sys-root/usr/include/c++/15/aarch64-redhat-linux"
ENV CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_RUSTFLAGS="-C link-arg=-L/usr/aarch64-linux-gnu/sys-root/lib64 -C link-arg=-L/usr/aarch64-linux-gnu/sys-root/usr/lib64 -C link-arg=-Wl,-rpath-link,/usr/aarch64-linux-gnu/sys-root/lib64 -C link-arg=-Wl,-rpath-link,/usr/aarch64-linux-gnu/sys-root/usr/lib64"
